Data Science Unit 1 Sprint 3 Assignment 1
Apply the t-test to real data
Your assignment is to determine which issues have "statistically significant" differences between political parties in this 1980s congressional voting data. The data consists of 435 instances (one for each congressperson), a class (democrat or republican), and 16 binary attributes (yes or no for voting for or against certain issues). Be aware - there are missing values!

df - https://archive.ics.uci.edu/ml/datasets/Congressional+Voting+Records

Your goals:

1. Load and clean the data (or determine the best method to drop observations when running tests)

2. Using hypothesis testing, find an issue that democrats support more than republicans with p < 0.01

3. Using hypothesis testing, find an issue that republicans support more than democrats with p < 0.01

4. Using hypothesis testing, find an issue where the difference between republicans and democrats has p > 0.1 (i.e. there may not be much of a difference)

Note that this data will involve 2 sample t-tests, because you're comparing averages across two groups (republicans and democrats) rather than a single group against a null hypothesis.

Stretch goals:

1. Refactor your code into functions so it's easy to rerun with arbitrary variables

2. Apply hypothesis testing to your personal project data (for the purposes of this notebook you can type a summary of the hypothesis you formed and tested)

In [1]:
import pandas as pd 

df = pd.read_csv('/Users/Data Copies/house-votes-84.data copy', header=None)

In [2]:
df.shape

(435, 17)

In [3]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
count,435,435,435,435,435,435,435,435,435,435,435,435,435,435,435,435,435
unique,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
top,democrat,n,y,y,n,y,y,y,y,y,y,n,n,y,y,n,y
freq,267,236,195,253,247,212,272,239,242,207,216,264,233,209,248,233,269

In [4]:
df.head()

           0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16
0  republican  n  y  n  y  y  y  n  n  n  y  ?  y  y  y  n  y
1  republican  n  y  n  y  y  y  n  n  n  n  n  y  y  y  n  ?
2    democrat  ?  y  y  ?  y  y  n  n  n  n  y  n  y  y  n  n
3    democrat  n  y  y  n  ?  y  n  n  n  n  y  n  y  n  n  y
4    democrat  y  y  y  n  y  y  n  n  n  n  y  ?  y  y  y  y

In [5]:
columns = ['Class Name', 'handicapped-infants', 'water-project-cost-sharing', 
           'adoption-of-the-budget-resolution', 'physician-fee-freeze', 
           'el-salvador-aid', 'religious-groups-in-schools', 
           'anti-satellite-test-ban','aid-to-nicaraguan-contras',
           'mx-missile', 'immigration', 'synfuels-corporation-cutback',
          'education-spending', 'superfund-right-to-sue', 
           'crime', 'duty-free-exports', 'export-administration-act-south-africa']

df = pd.read_csv('/Users/Data Copies/house-votes-84.data copy', names=columns)
df.head().T

,0,1,2,3,4
Class Name,republican,republican,democrat,democrat,democrat
handicapped-infants,n,n,?,n,y
water-project-cost-sharing,y,y,y,y,y
adoption-of-the-budget-resolution,n,n,y,y,y
physician-fee-freeze,y,y,?,n,n
el-salvador-aid,y,y,y,?,y
religious-groups-in-schools,y,y,y,y,y
anti-satellite-test-ban,n,n,n,n,n
aid-to-nicaraguan-contras,n,n,n,n,n
mx-missile,n,n,n,n,n
immigration,y,n,n,n,n
synfuels-corporation-cutback,?,n,y,y,y
education-spending,y,y,n,n,?
superfund-right-to-sue,y,y,y,y,y
crime,y,y,y,n,y
duty-free-exports,n,n,n,n,y
export-administration-act-south-africa,y,?,n,y,y

In [6]:
df.isnull().sum()

Class Name                                0
handicapped-infants                       0
water-project-cost-sharing                0
adoption-of-the-budget-resolution         0
physician-fee-freeze                      0
el-salvador-aid                           0
religious-groups-in-schools               0
anti-satellite-test-ban                   0
aid-to-nicaraguan-contras                 0
mx-missile                                0
immigration                               0
synfuels-corporation-cutback              0
education-spending                        0
superfund-right-to-sue                    0
crime                                     0
duty-free-exports                         0
export-administration-act-south-africa    0
dtype: int64

In [7]:
import numpy as np

df.replace('?', np.NaN, inplace = True)

In [8]:
df.isnull().sum()

Class Name                                  0
handicapped-infants                        12
water-project-cost-sharing                 48
adoption-of-the-budget-resolution          11
physician-fee-freeze                       11
el-salvador-aid                            15
religious-groups-in-schools                11
anti-satellite-test-ban                    14
aid-to-nicaraguan-contras                  15
mx-missile                                 22
immigration                                 7
synfuels-corporation-cutback               21
education-spending                         31
superfund-right-to-sue                     25
crime                                      17
duty-free-exports                          28
export-administration-act-south-africa    104
dtype: int64

In [9]:
df.head()

,Class Name,handicapped-infants,water-project-cost-sharing,adoption-of-the-budget-resolution,physician-fee-freeze,el-salvador-aid,religious-groups-in-schools,anti-satellite-test-ban,aid-to-nicaraguan-contras,mx-missile,immigration,synfuels-corporation-cutback,education-spending,superfund-right-to-sue,crime,duty-free-exports,export-administration-act-south-africa
0,republican,n,y,n,y,y,y,n,n,n,y,NaN,y,y,y,n,y
1,republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,NaN
2,democrat,NaN,y,y,NaN,y,y,n,n,n,n,y,n,y,y,n,n
3,democrat,n,y,y,n,NaN,y,n,n,n,n,y,n,y,n,n,y
4,democrat,y,y,y,n,y,y,n,n,n,n,y,NaN,y,y,y,y

In [24]:
rep = df[df['Class Name'] == 'republican']
rep.head()

,Class Name,handicapped-infants,water-project-cost-sharing,adoption-of-the-budget-resolution,physician-fee-freeze,el-salvador-aid,religious-groups-in-schools,anti-satellite-test-ban,aid-to-nicaraguan-contras,mx-missile,immigration,synfuels-corporation-cutback,education-spending,superfund-right-to-sue,crime,duty-free-exports,export-administration-act-south-africa
0,republican,n,y,n,y,y,y,n,n,n,y,NaN,y,y,y,n,y
1,republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,NaN
7,republican,n,y,n,y,y,y,n,n,n,n,n,n,y,y,NaN,y
8,republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,y
10,republican,n,y,n,y,y,n,n,n,n,n,NaN,NaN,y,y,n,n

In [25]:
dem = df[df['Class Name'] == 'democrat']
dem.head()

,Class Name,handicapped-infants,water-project-cost-sharing,adoption-of-the-budget-resolution,physician-fee-freeze,el-salvador-aid,religious-groups-in-schools,anti-satellite-test-ban,aid-to-nicaraguan-contras,mx-missile,immigration,synfuels-corporation-cutback,education-spending,superfund-right-to-sue,crime,duty-free-exports,export-administration-act-south-africa
2,democrat,NaN,y,y,NaN,y,y,n,n,n,n,y,n,y,y,n,n
3,democrat,n,y,y,n,NaN,y,n,n,n,n,y,n,y,n,n,y
4,democrat,y,y,y,n,y,y,n,n,n,n,y,NaN,y,y,y,y
5,democrat,n,y,y,n,y,y,n,n,n,n,n,n,y,y,y,y
6,democrat,n,y,n,y,y,y,n,n,n,n,n,n,NaN,y,y,y

2. Using hypothesis testing, find an issue that democrats support more than republicans with p < 0.01

In [26]:
from scipy.stats import ttest_ind, ttest_ind_from_stats, ttest_rel

In [37]:
dem.replace('n', 0, inplace = True)
dem.replace('y', 1, inplace = True)

rep.replace('n', 0, inplace = True)
rep.replace('y', 1, inplace = True)

In [43]:
print("Democrat Support: ", dem['duty-free-exports'].mean())
print("Republican Support: ", rep['duty-free-exports'].mean())

Democrat Support:  0.6374501992031872
Republican Support:  0.08974358974358974

In [44]:
ttest_ind(rep['duty-free-exports'], dem['duty-free-exports'], nan_policy='omit')

Ttest_indResult(statistic=-12.853146132542978, pvalue=5.997697174347365e-32)

3. Using hypothesis testing, find an issue that republicans support more than democrats with p < 0.01

In [38]:
print("Democrat Support: ", dem['physician-fee-freeze'].mean())
print("Republican Support: ", rep['physician-fee-freeze'].mean())

Democrat Support:  0.05405405405405406
Republican Support:  0.9878787878787879

In [45]:
ttest_ind(rep['physician-fee-freeze'], dem['physician-fee-freeze'], nan_policy='omit')

Ttest_indResult(statistic=49.36708157301406, pvalue=1.994262314074344e-177)

4. Using hypothesis testing, find an issue where the difference between republicans and democrats has p > 0.1 (i.e. there may not be much of a difference)

In [48]:
df.head().T

,0,1,2,3,4
Class Name,republican,republican,democrat,democrat,democrat
handicapped-infants,n,n,NaN,n,y
water-project-cost-sharing,y,y,y,y,y
adoption-of-the-budget-resolution,n,n,y,y,y
physician-fee-freeze,y,y,NaN,n,n
el-salvador-aid,y,y,y,NaN,y
religious-groups-in-schools,y,y,y,y,y
anti-satellite-test-ban,n,n,n,n,n
aid-to-nicaraguan-contras,n,n,n,n,n
mx-missile,n,n,n,n,n
immigration,y,n,n,n,n
synfuels-corporation-cutback,NaN,n,y,y,y
education-spending,y,y,n,n,NaN
superfund-right-to-sue,y,y,y,y,y
crime,y,y,y,n,y
duty-free-exports,n,n,n,n,y
export-administration-act-south-africa,y,NaN,n,y,y

In [50]:
print("Democrat Support: ", dem['water-project-cost-sharing'].mean())
print("Republican Support: ", rep['water-project-cost-sharing'].mean())

Democrat Support:  0.502092050209205
Republican Support:  0.5067567567567568

In [49]:
ttest_ind(rep['water-project-cost-sharing'], dem['water-project-cost-sharing'], nan_policy='omit')

Ttest_indResult(statistic=0.08896538137868286, pvalue=0.9291556823993485)